### ISSUE TITLE
Time to revive?

### ISSUE THREAD

**Issue by ArnoutVerbeken** [ReneNulschDE/mercedesmejsonpy#1]
Hello,

As it seems that Mercedes Me has put the API open again (at least experimental, and for production in the near future), do you think you could revive this?

https://developer.mercedes-benz.com/apis/connected_vehicle_experimental_api

Thanks in advance

**Comment by ReneNulschDE** [comment]
Hi, sorry missed your issue. This code base is already working with this experimental_api. So you could play with your test cars.

**Comment by ReneNulschDE** [comment]
Hi,

please take a look in this beta lib:
https://github.com/ReneNulschDE/HA_CC_MercedesME_Beta

this is the implementation against the new api.

BR
Rene
